myProject/Models/ORDER_tbl.cs
namespace myProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class ORDER_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDER_tbl()
        {
            C0RDER_DETAIL_tbl = new HashSet<C0RDER_DETAIL_tbl>();
        }

        [Key]
        public int ORDER_ID { get; set; }

        public DateTime ORDER_DATE { get; set; }

        public int SHOP_FID { get; set; }

        public int CUSTOMER_FID { get; set; }

        [Required]
        [StringLength(50)]
        public string ORDER_STATUS { get; set; }

        [Required]
        [StringLength(50)]
        public string PAYMENT_MODE { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C0RDER_DETAIL_tbl> C0RDER_DETAIL_tbl { get; set; }

        public virtual CUSTOMER_tbl CUSTOMER_tbl { get; set; }

        public virtual SHOP_tbl SHOP_tbl { get; set; }
    }
}

myProject/Controllers/ADMIN_tblController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using myProject.Models;

namespace myProject.Controllers
{
    public class ADMIN_tblController : Controller
    {
        private Model1 db = new Model1();

        // GET: ADMIN_tbl
        public ActionResult Index()
        {
            return View(db.ADMIN_tbl.ToList());
        }

        // GET: ADMIN_tbl/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ADMIN_tbl aDMIN_tbl = db.ADMIN_tbl.Find(id);
            if (aDMIN_tbl == null)
            {
                return HttpNotFound();
            }
            return View(aDMIN_tbl);
        }

        // GET: ADMIN_tbl/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ADMIN_tbl/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ADMIN_ID,ADMIN_NAME,ADMIN_EMAIL,ADMIN_PASSWORD,ADMIN_CONTACT,ADMIN_ADDRESS")] ADMIN_tbl aDMIN_tbl)
        {
            if (ModelState.IsValid)
            {
                db.ADMIN_tbl.Add(aDMIN_tbl);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(aDMIN_tbl);
        }

        // GET: ADMIN_tbl/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ADMIN_tbl aDMIN_tbl = db.ADMIN_tbl.Find(id);
            if (aDMIN_tbl == null)
            {
                return HttpNotFound();
            }
            return View(aDMIN_tbl);
        }

        // POST: ADMIN_tbl/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ADMIN_ID,ADMIN_NAME,ADMIN_EMAIL,ADMIN_PASSWORD,ADMIN_CONTACT,ADMIN_ADDRESS")] ADMIN_tbl aDMIN_tbl)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aDMIN_tbl).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(aDMIN_tbl);
        }

        // GET: ADMIN_tbl/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ADMIN_tbl aDMIN_tbl = db.ADMIN_tbl.Find(id);
            if (aDMIN_tbl == null)
            {
                return HttpNotFound();
            }
            return View(aDMIN_tbl);
        }

        // POST: ADMIN_tbl/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ADMIN_tbl aDMIN_tbl = db.ADMIN_tbl.Find(id);
            db.ADMIN_tbl.Remove(aDMIN_tbl);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

myProject/Controllers/ORDER_tblController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using myProject.Models;

namespace myProject.Controllers
{
    public class ORDER_tblController : Controller
    {
        private Model1 db = new Model1();

        // GET: ORDER_tbl
        public ActionResult Index()
        {
            var oRDER_tbl = db.ORDER_tbl.Include(o => o.CUSTOMER_tbl).Include(o => o.SHOP_tbl);
            return View(oRDER_tbl.ToList());
        }

        // GET: ORDER_tbl/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ORDER_tbl oRDER_tbl = db.ORDER_tbl.Find(id);
            if (oRDER_tbl == null)
            {
                return HttpNotFound();
            }
            return View(oRDER_tbl);
        }

        // GET: ORDER_tbl/Create
        public ActionResult Create()
        {
            ViewBag.CUSTOMER_FID = new SelectList(db.CUSTOMER_tbl, "CUSTOMER_ID", "CUSTOMER_NAME");
            ViewBag.SHOP_FID = new SelectList(db.SHOP_tbl, "SHOP_ID", "SHOP_NAME");
            return View();
        }

        // POST: ORDER_tbl/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ORDER_ID,ORDER_DATE,SHOP_FID,CUSTOMER_FID,ORDER_STATUS,PAYMENT_MODE")] ORDER_tbl oRDER_tbl)
        {
            if (ModelState.IsValid)
            {
                db.ORDER_tbl.Add(oRDER_tbl);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CUSTOMER_FID = new SelectList(db.CUSTOMER_tbl, "CUSTOMER_ID", "CUSTOMER_NAME", oRDER_tbl.CUSTOMER_FID);
            ViewBag.SHOP_FID = new SelectList(db.SHOP_tbl, "SHOP_ID", "SHOP_NAME", oRDER_tbl.SHOP_FID);
            return View(oRDER_tbl);
        }

        // GET: ORDER_tbl/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ORDER_tbl oRDER_tbl = db.ORDER_tbl.Find(id);
            if (oRDER_tbl == null)
            {
                return HttpNotFound();
            }
            ViewBag.CUSTOMER_FID = new SelectList(db.CUSTOMER_tbl, "CUSTOMER_ID", "CUSTOMER_NAME", oRDER_tbl.CUSTOMER_FID);
            ViewBag.SHOP_FID = new SelectList(db.SHOP_tbl, "SHOP_ID", "SHOP_NAME", oRDER_tbl.SHOP_FID);
            return View(oRDER_tbl);
        }

        // POST: ORDER_tbl/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ORDER_ID,ORDER_DATE,SHOP_FID,CUSTOMER_FID,ORDER_STATUS,PAYMENT_MODE")] ORDER_tbl oRDER_tbl)
        {
            if (ModelState.IsValid)
            {
                db.Entry(oRDER_tbl).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CUSTOMER_FID = new SelectList(db.CUSTOMER_tbl, "CUSTOMER_ID", "CUSTOMER_NAME", oRDER_tbl.CUSTOMER_FID);
            ViewBag.SHOP_FID = new SelectList(db.SHOP_tbl, "SHOP_ID", "SHOP_NAME", oRDER_tbl.SHOP_FID);
            return View(oRDER_tbl);
        }

        // GET: ORDER_tbl/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ORDER_tbl oRDER_tbl = db.ORDER_tbl.Find(id);
            if (oRDER_tbl == null)
            {
                return HttpNotFound();
            }
            return View(oRDER_tbl);
        }

        // POST: ORDER_tbl/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ORDER_tbl oRDER_tbl = db.ORDER_tbl.Find(id);
            db.ORDER_tbl.Remove(oRDER_tbl);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

myProject/Views/ORDER_tbl/Create.cshtml
@model myProject.Models.ORDER_tbl

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ORDER_tbl</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ORDER_DATE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ORDER_DATE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ORDER_DATE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SHOP_FID, "SHOP_FID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SHOP_FID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SHOP_FID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CUSTOMER_FID, "CUSTOMER_FID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CUSTOMER_FID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CUSTOMER_FID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ORDER_STATUS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ORDER_STATUS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ORDER_STATUS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PAYMENT_MODE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PAYMENT_MODE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PAYMENT_MODE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

myProject/Views/ORDER_tbl/Delete.cshtml
@model myProject.Models.ORDER_tbl

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ORDER_tbl</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CUSTOMER_tbl.CUSTOMER_NAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CUSTOMER_tbl.CUSTOMER_NAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SHOP_tbl.SHOP_NAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SHOP_tbl.SHOP_NAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ORDER_DATE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ORDER_DATE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ORDER_STATUS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ORDER_STATUS)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PAYMENT_MODE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PAYMENT_MODE)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

myProject/Views/ORDER_tbl/Details.cshtml
@model myProject.Models.ORDER_tbl

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ORDER_tbl</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CUSTOMER_tbl.CUSTOMER_NAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CUSTOMER_tbl.CUSTOMER_NAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SHOP_tbl.SHOP_NAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SHOP_tbl.SHOP_NAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ORDER_DATE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ORDER_DATE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ORDER_STATUS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ORDER_STATUS)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PAYMENT_MODE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PAYMENT_MODE)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ORDER_ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

myProject/Views/ORDER_tbl/Edit.cshtml
@model myProject.Models.ORDER_tbl

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ORDER_tbl</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ORDER_ID)

        <div class="form-group">
            @Html.LabelFor(model => model.ORDER_DATE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ORDER_DATE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ORDER_DATE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SHOP_FID, "SHOP_FID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SHOP_FID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SHOP_FID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CUSTOMER_FID, "CUSTOMER_FID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CUSTOMER_FID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CUSTOMER_FID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ORDER_STATUS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ORDER_STATUS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ORDER_STATUS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PAYMENT_MODE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PAYMENT_MODE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PAYMENT_MODE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

myProject/Views/ORDER_tbl/Index.cshtml
@model IEnumerable<myProject.Models.ORDER_tbl>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    <a href="@Url.Action("Create","ORDER_tbl")" class="btn btn-danger">Create New</a>
</p>
<table class="table">
    <tr>
        <th>
            Customer Name 
        </th>
        <th>
            Shop Name
        </th>
        <th>
            Order Date
        </th>
        <th>
            Order Status
        </th>
        <th>
            Payment Mode
        </th>
        <th></th>
    </tr>

@foreach (var order in Model) {
    <tr>
        <td>
            order.CUSTOMER_tbl.CUSTOMER_NAME
        </td>
        <td>
            order.SHOP_tbl.SHOP_NAME
        </td>
        <td>
          order.ORDER_DATE
        </td>
        <td>
            order.ORDER_STATUS
        </td>
        <td>
            order.PAYMENT_MODE
        </td>
        <td>
            <a class="glyphicon glyphicon-pencil btn bntn-danger" href="@Url.Action("Edit", "ADMIN_tbl", new { id = order.ORDER_ID })">Edit</a>
            <a class="glyphicon glyphicon-book btn bntn-danger" href="@Url.Action("Edit", "ADMIN_tbl", new { id = order.ORDER_ID })">Details</a>
            <a class="glyphicon glyphicon-trash btn bntn-danger" href="@Url.Action("Edit", "ADMIN_tbl", new { id = order.ORDER_ID })">Delete</a>

        </td>
    </tr>
}

</table>