myProject/Models/SHOPKEEPER_tbl.cs
namespace myProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class SHOPKEEPER_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SHOPKEEPER_tbl()
        {
            S_FEEDBACK_tbl = new HashSet<S_FEEDBACK_tbl>();
            SHOP_tbl = new HashSet<SHOP_tbl>();
        }

        [Key]
        public int SHOPKEEPER_ID { get; set; }

        [Required]
        [StringLength(50)]
        public string SHOPKEEPER_NAME { get; set; }

        [Required]
        [StringLength(50)]
        public string SHOPKEEPER_CONTACT { get; set; }

        [Required]
        [StringLength(50)]
        public string SHOPKEEPER_CNIC { get; set; }

        [Required]
        [StringLength(50)]
        public string SHOPKEEPER_EMAIL { get; set; }

        [Required]
        [StringLength(50)]
        public string SHOPKEEPER_PASSWORD { get; set; }

        [Required]
        [StringLength(300)]
        public string SHOPKEEPER_ADDRESS { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<S_FEEDBACK_tbl> S_FEEDBACK_tbl { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SHOP_tbl> SHOP_tbl { get; set; }
    }
}

myProject/Controllers/SHOPKEEPER_tblController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using myProject.Models;

namespace myProject.Controllers
{
    public class SHOPKEEPER_tblController : Controller
    {
        private Model1 db = new Model1();

        // GET: SHOPKEEPER_tbl
        public ActionResult Index()
        {
            return View(db.SHOPKEEPER_tbl.ToList());
        }

        // GET: SHOPKEEPER_tbl/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SHOPKEEPER_tbl sHOPKEEPER_tbl = db.SHOPKEEPER_tbl.Find(id);
            if (sHOPKEEPER_tbl == null)
            {
                return HttpNotFound();
            }
            return View(sHOPKEEPER_tbl);
        }

        // GET: SHOPKEEPER_tbl/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SHOPKEEPER_tbl/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SHOPKEEPER_ID,SHOPKEEPER_NAME,SHOPKEEPER_CONTACT,SHOPKEEPER_CNIC,SHOPKEEPER_EMAIL,SHOPKEEPER_PASSWORD,SHOPKEEPER_ADDRESS")] SHOPKEEPER_tbl sHOPKEEPER_tbl)
        {
            if (ModelState.IsValid)
            {
                db.SHOPKEEPER_tbl.Add(sHOPKEEPER_tbl);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(sHOPKEEPER_tbl);
        }

        // GET: SHOPKEEPER_tbl/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SHOPKEEPER_tbl sHOPKEEPER_tbl = db.SHOPKEEPER_tbl.Find(id);
            if (sHOPKEEPER_tbl == null)
            {
                return HttpNotFound();
            }
            return View(sHOPKEEPER_tbl);
        }

        // POST: SHOPKEEPER_tbl/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SHOPKEEPER_ID,SHOPKEEPER_NAME,SHOPKEEPER_CONTACT,SHOPKEEPER_CNIC,SHOPKEEPER_EMAIL,SHOPKEEPER_PASSWORD,SHOPKEEPER_ADDRESS")] SHOPKEEPER_tbl sHOPKEEPER_tbl)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sHOPKEEPER_tbl).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(sHOPKEEPER_tbl);
        }

        // GET: SHOPKEEPER_tbl/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SHOPKEEPER_tbl sHOPKEEPER_tbl = db.SHOPKEEPER_tbl.Find(id);
            if (sHOPKEEPER_tbl == null)
            {
                return HttpNotFound();
            }
            return View(sHOPKEEPER_tbl);
        }

        // POST: SHOPKEEPER_tbl/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SHOPKEEPER_tbl sHOPKEEPER_tbl = db.SHOPKEEPER_tbl.Find(id);
            db.SHOPKEEPER_tbl.Remove(sHOPKEEPER_tbl);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

myProject/Views/SHOPKEEPER_tbl/Create.cshtml
@model myProject.Models.SHOPKEEPER_tbl

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SHOPKEEPER_tbl</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SHOPKEEPER_NAME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SHOPKEEPER_NAME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SHOPKEEPER_NAME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SHOPKEEPER_CONTACT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SHOPKEEPER_CONTACT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SHOPKEEPER_CONTACT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SHOPKEEPER_CNIC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SHOPKEEPER_CNIC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SHOPKEEPER_CNIC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SHOPKEEPER_EMAIL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SHOPKEEPER_EMAIL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SHOPKEEPER_EMAIL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SHOPKEEPER_PASSWORD, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SHOPKEEPER_PASSWORD, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SHOPKEEPER_PASSWORD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SHOPKEEPER_ADDRESS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SHOPKEEPER_ADDRESS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SHOPKEEPER_ADDRESS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

myProject/Views/SHOPKEEPER_tbl/Delete.cshtml
@model myProject.Models.SHOPKEEPER_tbl

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SHOPKEEPER_tbl</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SHOPKEEPER_NAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SHOPKEEPER_NAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SHOPKEEPER_CONTACT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SHOPKEEPER_CONTACT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SHOPKEEPER_CNIC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SHOPKEEPER_CNIC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SHOPKEEPER_EMAIL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SHOPKEEPER_EMAIL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SHOPKEEPER_PASSWORD)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SHOPKEEPER_PASSWORD)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SHOPKEEPER_ADDRESS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SHOPKEEPER_ADDRESS)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

myProject/Views/SHOPKEEPER_tbl/Details.cshtml
@model myProject.Models.SHOPKEEPER_tbl

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>SHOPKEEPER_tbl</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SHOPKEEPER_NAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SHOPKEEPER_NAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SHOPKEEPER_CONTACT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SHOPKEEPER_CONTACT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SHOPKEEPER_CNIC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SHOPKEEPER_CNIC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SHOPKEEPER_EMAIL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SHOPKEEPER_EMAIL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SHOPKEEPER_PASSWORD)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SHOPKEEPER_PASSWORD)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SHOPKEEPER_ADDRESS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SHOPKEEPER_ADDRESS)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.SHOPKEEPER_ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

myProject/Views/SHOPKEEPER_tbl/Edit.cshtml
@model myProject.Models.SHOPKEEPER_tbl

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SHOPKEEPER_tbl</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SHOPKEEPER_ID)

        <div class="form-group">
            @Html.LabelFor(model => model.SHOPKEEPER_NAME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SHOPKEEPER_NAME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SHOPKEEPER_NAME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SHOPKEEPER_CONTACT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SHOPKEEPER_CONTACT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SHOPKEEPER_CONTACT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SHOPKEEPER_CNIC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SHOPKEEPER_CNIC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SHOPKEEPER_CNIC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SHOPKEEPER_EMAIL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SHOPKEEPER_EMAIL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SHOPKEEPER_EMAIL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SHOPKEEPER_PASSWORD, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SHOPKEEPER_PASSWORD, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SHOPKEEPER_PASSWORD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SHOPKEEPER_ADDRESS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SHOPKEEPER_ADDRESS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SHOPKEEPER_ADDRESS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

myProject/Views/SHOPKEEPER_tbl/Index.cshtml
@model IEnumerable<myProject.Models.SHOPKEEPER_tbl>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    <a href="@Url.Action("Create","SHOPKEEPER_tbl")" class="btn btn-danger">Create New</a>
</p>
<table class="table">
    <tr>
        <th>
            Shopkeeper Name
        </th>
        <th>
         Shopkeeper Contact
        </th>
        <th>
          Shopkeeper CNIC
        </th>
        <th>
            Shopkeeper Email
        </th>
        <th>
           Shopkeeper Password
        </th>
        <th>
            Shopkeeper Address
        </th>
        <th></th>
    </tr>

@foreach (var shopkeeper in Model) {
    <tr>
        <td>
            @shopkeeper.SHOPKEEPER_NAME
        </td>
        <td>
           @shopkeeper.SHOPKEEPER_CONTACT
        </td>
        <td>
            @shopkeeper.SHOPKEEPER_CNIC
        </td>
        <td>
             @shopkeeper.SHOPKEEPER_EMAIL
        </td>
        <td>
             @shopkeeper.SHOPKEEPER_PASSWORD
        </td>
        <td>
             @shopkeeper.SHOPKEEPER_ADDRESS
        </td>
        <td>
            <a class="glyphicon glyphicon-pencil btn btn-danger square-btn-adjust" href="@Url.Action("Edit", "SHOPKEEPER_tbl", new { id = shopkeeper.SHOPKEEPER_ID })"></a>
            <a class="glyphicon glyphicon-book btn btn-danger square-btn-adjust"   href="@Url.Action("Details", "SHOPKEEPER_tbl", new { id = shopkeeper.SHOPKEEPER_ID})"></a>
            <a class="glyphicon glyphicon-trash btn btn-danger square-btn-adjust"   href="@Url.Action("Delete", "SHOPKEEPER_tbl", new { id = shopkeeper.SHOPKEEPER_ID })"></a>

           
        </td>
    </tr>
}

</table>