myProject/Models/PRODUCT_tbl.cs
namespace myProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class PRODUCT_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT_tbl()
        {
            C0RDER_DETAIL_tbl = new HashSet<C0RDER_DETAIL_tbl>();
        }

        [Key]
        public int PRODUCT_ID { get; set; }
        [NotMapped]
        public int Quantity { get; set; }

        [Required]
        [StringLength(50)]
        public string PRODUCT_NAME { get; set; }

        
        [StringLength(300)]
        public string PRODUCT_IMAGE { get; set; }

        [Required]
        [StringLength(50)]
        public string PRODUCT_DESCRIPTION { get; set; }

        [Column(TypeName = "numeric")]
        public decimal PRODUCT_PURCHASEPRICE { get; set; }

        [Column(TypeName = "numeric")]
        public decimal PRODUCT_SALEPRICE { get; set; }

        [Required]
        [StringLength(50)]
        public string PRODUCT_AVAILABILITY { get; set; }

        public int P_CATEGORY_FID { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C0RDER_DETAIL_tbl> C0RDER_DETAIL_tbl { get; set; }

        public virtual P_CATEGORY_tbl P_CATEGORY_tbl { get; set; }
    }
}

myProject/Controllers/PRODUCT_tblController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using myProject.Models;

namespace myProject.Controllers
{
    public class PRODUCT_tblController : Controller
    {
        private Model1 db = new Model1();

        // GET: PRODUCT_tbl
        public ActionResult Index()
        {
            var pRODUCT_tbl = db.PRODUCT_tbl.Include(p => p.P_CATEGORY_tbl);
            return View(pRODUCT_tbl.ToList());
        }

        // GET: PRODUCT_tbl/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PRODUCT_tbl pRODUCT_tbl = db.PRODUCT_tbl.Find(id);
            if (pRODUCT_tbl == null)
            {
                return HttpNotFound();
            }
            return View(pRODUCT_tbl);
        }

        // GET: PRODUCT_tbl/Create
        public ActionResult Create()
        {
            ViewBag.P_CATEGORY_FID = new SelectList(db.P_CATEGORY_tbl, "P_CATEGORY_ID", "P_CATEGORY_NAME");
            return View();
        }

        // POST: PRODUCT_tbl/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PRODUCT_tbl pRODUCT_tbl,HttpPostedFileBase imag)
        {
            string fullpath=Server.MapPath("~/Content/ProjectImages/"+imag.FileName);
            imag.SaveAs(fullpath);
            pRODUCT_tbl.PRODUCT_IMAGE = "~/Content/ProjectImages/" + imag.FileName;

            if (ModelState.IsValid)
            {
                db.PRODUCT_tbl.Add(pRODUCT_tbl);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.P_CATEGORY_FID = new SelectList(db.P_CATEGORY_tbl, "P_CATEGORY_ID", "P_CATEGORY_NAME", pRODUCT_tbl.P_CATEGORY_FID);
            return View(pRODUCT_tbl);
        }

        // GET: PRODUCT_tbl/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PRODUCT_tbl pRODUCT_tbl = db.PRODUCT_tbl.Find(id);
            if (pRODUCT_tbl == null)
            {
                return HttpNotFound();
            }
            ViewBag.CATEGORY_FID = new SelectList(db.P_CATEGORY_tbl, "P_CATEGORY_ID", "P_CATEGORY_NAME", pRODUCT_tbl.P_CATEGORY_FID);
            return View(pRODUCT_tbl);
        }

        // POST: PRODUCT_tbl/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PRODUCT_tbl pRODUCT_tbl, HttpPostedFileBase imag)
        { 
            if (imag != null)
            {
                string fullpath = Server.MapPath("~/Content/ProjectImages/" + imag.FileName);
                imag.SaveAs(fullpath);
                pRODUCT_tbl.PRODUCT_IMAGE = "~/Content/ProjectImages/" + imag.FileName;
            }
            if (ModelState.IsValid)
            {
                db.Entry(pRODUCT_tbl).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.P_CATEGORY_FID = new SelectList(db.P_CATEGORY_tbl, "P_CATEGORY_ID", "P_CATEGORY_NAME", pRODUCT_tbl.P_CATEGORY_FID);
            return View(pRODUCT_tbl);
        }

        // GET: PRODUCT_tbl/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PRODUCT_tbl pRODUCT_tbl = db.PRODUCT_tbl.Find(id);
            if (pRODUCT_tbl == null)
            {
                return HttpNotFound();
            }
            return View(pRODUCT_tbl);
        }

        // POST: PRODUCT_tbl/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PRODUCT_tbl pRODUCT_tbl = db.PRODUCT_tbl.Find(id);
            db.PRODUCT_tbl.Remove(pRODUCT_tbl);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

myProject/Views/PRODUCT_tbl/Create.cshtml
@model myProject.Models.PRODUCT_tbl

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "PRODUCT_tbl", FormMethod.Post, new {enctype="multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PRODUCT_tbl</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PRODUCT_NAME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PRODUCT_NAME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PRODUCT_NAME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PRODUCT_IMAGE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               <input type="file" name="imag" required accept="img/*"/>

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PRODUCT_DESCRIPTION, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PRODUCT_DESCRIPTION, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PRODUCT_DESCRIPTION, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PRODUCT_PURCHASEPRICE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PRODUCT_PURCHASEPRICE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PRODUCT_PURCHASEPRICE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PRODUCT_SALEPRICE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PRODUCT_SALEPRICE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PRODUCT_SALEPRICE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PRODUCT_AVAILABILITY, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PRODUCT_AVAILABILITY, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PRODUCT_AVAILABILITY, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.P_CATEGORY_FID, "P_CATEGORY_FID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("P_CATEGORY_FID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.P_CATEGORY_FID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

myProject/Views/PRODUCT_tbl/Delete.cshtml
@model myProject.Models.PRODUCT_tbl

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PRODUCT_tbl</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.P_CATEGORY_tbl.P_CATEGORY_NAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.P_CATEGORY_tbl.P_CATEGORY_NAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PRODUCT_NAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PRODUCT_NAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PRODUCT_IMAGE)
           
        </dt>

        <dd>
            @Html.HiddenFor(model => model.PRODUCT_IMAGE)
            <img src="@Url.Content(Model.PRODUCT_IMAGE)" width="100" height="100"/>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PRODUCT_DESCRIPTION)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PRODUCT_DESCRIPTION)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PRODUCT_PURCHASEPRICE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PRODUCT_PURCHASEPRICE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PRODUCT_SALEPRICE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PRODUCT_SALEPRICE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PRODUCT_AVAILABILITY)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PRODUCT_AVAILABILITY)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

myProject/Views/PRODUCT_tbl/Details.cshtml
@model myProject.Models.PRODUCT_tbl

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>PRODUCT_tbl</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.P_CATEGORY_tbl.P_CATEGORY_NAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.P_CATEGORY_tbl.P_CATEGORY_NAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PRODUCT_NAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PRODUCT_NAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PRODUCT_IMAGE)
        </dt>

        <dd>
            <img src="@Url.Content(Model.PRODUCT_IMAGE)" width="100" height="100"/>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PRODUCT_DESCRIPTION)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PRODUCT_DESCRIPTION)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PRODUCT_PURCHASEPRICE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PRODUCT_PURCHASEPRICE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PRODUCT_SALEPRICE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PRODUCT_SALEPRICE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PRODUCT_AVAILABILITY)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PRODUCT_AVAILABILITY)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PRODUCT_ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

myProject/Views/PRODUCT_tbl/Edit.cshtml
@model myProject.Models.PRODUCT_tbl

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "PRODUCT_tbl", FormMethod.Post, new { enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PRODUCT_tbl</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PRODUCT_ID)
        @*<input type="hidden" name="PRODUCT_ID" value="Model.PRODUCT_ID"/>*@

        <div class="form-group">
            @Html.LabelFor(model => model.PRODUCT_NAME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.EditorFor(model => model.PRODUCT_NAME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PRODUCT_NAME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PRODUCT_IMAGE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="imag" />
                <img src="@Url.Content(Model.PRODUCT_IMAGE)" />

                @Html.HiddenFor(model => model.PRODUCT_IMAGE, new { htmlAttributes = new { @class = "form-control", @readonly = "", } })
                @Html.ValidationMessageFor(model => model.PRODUCT_IMAGE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PRODUCT_DESCRIPTION, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PRODUCT_DESCRIPTION, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PRODUCT_DESCRIPTION, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PRODUCT_PURCHASEPRICE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PRODUCT_PURCHASEPRICE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PRODUCT_PURCHASEPRICE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PRODUCT_SALEPRICE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PRODUCT_SALEPRICE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PRODUCT_SALEPRICE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PRODUCT_AVAILABILITY, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PRODUCT_AVAILABILITY, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PRODUCT_AVAILABILITY, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.P_CATEGORY_FID, "P_CATEGORY_FID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("P_CATEGORY_FID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.P_CATEGORY_FID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

myProject/Views/PRODUCT_tbl/Index.cshtml
@model IEnumerable<myProject.Models.PRODUCT_tbl>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    <a href="@Url.Action("Create","PRODUCT_tbl")" class="btn btn-danger ">Create New</a>
</p>
<table class="table">
    <tr>
        <th>
           Category Name
        </th>
        <th>
            Product Name
        </th>
        <th>
           Product Image
        </th>
        <th>
            Product Description
        </th>
        <th>
            Purchase-Price
        </th>
        <th>
            Sale-Price
        </th>
        <th>
            Product Availability
        </th>
        <th></th>
    </tr>

@foreach (var product in Model) {
    <tr>
        <td>
            @product.P_CATEGORY_tbl.P_CATEGORY_NAME
        </td>
        <td>
            @product.PRODUCT_NAME
        </td>
        <td>
            
            <img src="@Url.Content(product.PRODUCT_IMAGE)" width="100" height="100"/>
        </td>
        <td>
            @product.PRODUCT_DESCRIPTION
        </td>
        <td>
            @product.PRODUCT_PURCHASEPRICE
        </td>
        <td>
            @product.PRODUCT_SALEPRICE
        </td>
        <td>
            @product.PRODUCT_AVAILABILITY
        </td>
        <td>
            <a class="glyphicon glyphicon-pencil btn btn-danger square-btn-adjust" href="@Url.Action("Edit", "PRODUCT_tbl", new { id = product.PRODUCT_ID})"></a>
            <a class="glyphicon glyphicon-book btn btn-danger square-btn-adjust"   href="@Url.Action("DETAILS", "PRODUCT_tbl", new { id = product.PRODUCT_ID })"></a>
            <a class="glyphicon glyphicon-trash btn btn-danger square-btn-adjust"  href="@Url.Action("Delete", "PRODUCT_tbl", new { id = product.PRODUCT_ID })"></a>

            @*@Html.ActionLink("Edit", "Edit", new { id = product.PRODUCT_ID }) |
            @Html.ActionLink("Details", "Details", new { id = product.PRODUCT_ID }) |
            @Html.ActionLink("Delete", "Delete", new { id = product.PRODUCT_ID })*@
        </td>
    </tr>
}

</table>