myProject/Models/SHOP_tbl.cs
namespace myProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class SHOP_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SHOP_tbl()
        {
            P_CATEGORY_tbl = new HashSet<P_CATEGORY_tbl>();
            ORDER_tbl = new HashSet<ORDER_tbl>(); 
           
        }

        [Key]
        public int SHOP_ID { get; set; }

        [Required]
        [StringLength(50)]
        public string SHOP_NAME { get; set; }
        
       
        [StringLength(500)]
        public string SHOP_IMAGE { get; set; }
        

        [Required]
        [StringLength(300)]
        public string SHOP_ADDRESS { get; set; }

       

        [Required]
        [StringLength(50)]
        public string SHOP_RENT { get; set; }

        public int SHOPKEEPER_FID { get; set; }
        public int SHP_CATEGORY_FID { get; set; }

        public int CITY_FID { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_CATEGORY_tbl> P_CATEGORY_tbl { get; set; }

        public virtual CITY_tbl CITY_tbl { get; set; }

        public virtual SHP_CATEGORY_tbl SHP_CATEGORY_tbl { get; set; }
        

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_tbl> ORDER_tbl { get; set; }

        public virtual SHOPKEEPER_tbl SHOPKEEPER_tbl { get; set; }

        
    }
}

myProject/Controllers/SHOP_tblController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using myProject.Models;

namespace myProject.Controllers
{
    public class SHOP_tblController : Controller
    {
        private Model1 db = new Model1();

        // GET: SHOP_tbl
        public ActionResult Index()
        {
            var sHOP_tbl = db.SHOP_tbl.Include(s => s.CITY_tbl).Include(s => s.SHP_CATEGORY_tbl).Include(s => s.SHOPKEEPER_tbl);
            return View(sHOP_tbl.ToList());
        }

        // GET: SHOP_tbl/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SHOP_tbl sHOP_tbl = db.SHOP_tbl.Find(id);
            if (sHOP_tbl == null)
            {
                return HttpNotFound();
            }
            return View(sHOP_tbl);
        }

        // GET: SHOP_tbl/Create
        public ActionResult Create()
        {
            ViewBag.CITY_FID = new SelectList(db.CITY_tbl, "CITY_ID", "CITY_NAME");
            ViewBag.SHP_CATEGORY_FID = new SelectList(db.SHP_CATEGORY_tbl, "SHP_CATEGORY_ID", "SHP_CATEGORY_NAME", "SHP_CATEGORY_STATUS");
            ViewBag.SHOPKEEPER_FID = new SelectList(db.SHOPKEEPER_tbl, "SHOPKEEPER_ID", "SHOPKEEPER_NAME");
            return View();
        }

        // POST: SHOP_tbl/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( SHOP_tbl sHOP_tbl, HttpPostedFileBase pic)
        {
                string path = Server.MapPath("~/Content/ProjectImages/" + pic.FileName);
                pic.SaveAs(path);
                sHOP_tbl.SHOP_IMAGE = "~/Content/ProjectImages/" + pic.FileName;
            

            if (ModelState.IsValid)
            {
                db.SHOP_tbl.Add(sHOP_tbl);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CITY_FID = new SelectList(db.CITY_tbl, "CITY_ID", "CITY_NAME", sHOP_tbl.CITY_FID);
            ViewBag.SHP_CATEGORY_FID = new SelectList(db.SHP_CATEGORY_tbl, "SHP_CATEGORY_ID", "SHP_CATEGORY_NAME", "SHP_CATEGORY_STATUS", sHOP_tbl.SHP_CATEGORY_FID);
            ViewBag.SHOPKEEPER_FID = new SelectList(db.SHOPKEEPER_tbl, "SHOPKEEPER_ID", "SHOPKEEPER_NAME", sHOP_tbl.SHOPKEEPER_FID);
            return View(sHOP_tbl);
        }

        // GET: SHOP_tbl/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SHOP_tbl sHOP_tbl = db.SHOP_tbl.Find(id);
            if (sHOP_tbl == null)
            {
                return HttpNotFound();
            }
            ViewBag.CITY_FID = new SelectList(db.CITY_tbl, "CITY_ID", "CITY_NAME", sHOP_tbl.CITY_FID);
            ViewBag.FLOOR_FID = new SelectList(db.SHP_CATEGORY_tbl, "FLOOR_ID", "FLOOR_NAME", sHOP_tbl.SHP_CATEGORY_FID);
            ViewBag.SHOPKEEPER_FID = new SelectList(db.SHOPKEEPER_tbl, "SHOPKEEPER_ID", "SHOPKEEPER_NAME", sHOP_tbl.SHOPKEEPER_FID);
            return View(sHOP_tbl);
        }

        // POST: SHOP_tbl/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SHOP_tbl sHOP_tbl, HttpPostedFileBase pic)
        {
            if (pic != null)
            {
                string path = Server.MapPath("~/Content/ProjectImages/" + pic.FileName);
                pic.SaveAs(path);
                sHOP_tbl.SHOP_IMAGE = "~/Content/ProjectImages/" + pic.FileName;
            }

            if (ModelState.IsValid)
            {
                db.Entry(sHOP_tbl).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CITY_FID = new SelectList(db.CITY_tbl, "CITY_ID", "CITY_NAME", sHOP_tbl.CITY_FID);
            ViewBag.FLOOR_FID = new SelectList(db.SHP_CATEGORY_tbl, "SHP_CATEGORY_ID", "SHP_CATEGORY_NAME", "SHP_CATEGORY_ICON", "SHP_CATEGORY_STATUS", sHOP_tbl.SHP_CATEGORY_FID);
            ViewBag.SHOPKEEPER_FID = new SelectList(db.SHOPKEEPER_tbl, "SHOPKEEPER_ID", "SHOPKEEPER_NAME", sHOP_tbl.SHOPKEEPER_FID);
            return View(sHOP_tbl);
        }

        // GET: SHOP_tbl/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SHOP_tbl sHOP_tbl = db.SHOP_tbl.Find(id);
            if (sHOP_tbl == null)
            {
                return HttpNotFound();
            }
            return View(sHOP_tbl);
        }

        // POST: SHOP_tbl/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SHOP_tbl sHOP_tbl = db.SHOP_tbl.Find(id);
            db.SHOP_tbl.Remove(sHOP_tbl);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

myProject/Views/SHOP_tbl/Create.cshtml
@model myProject.Models.SHOP_tbl

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create","SHOP_tbl",FormMethod.Post,new {enctype="multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SHOP_tbl</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SHOP_NAME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SHOP_NAME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SHOP_NAME, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.SHOP_IMAGE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="pic" required accept="img/*" />

                @Html.HiddenFor(model => model.SHOP_IMAGE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SHOP_IMAGE, "", new { @class = "text-danger" })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SHOP_ADDRESS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SHOP_ADDRESS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SHOP_ADDRESS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SHP_CATEGORY_FID, "SHP_CATEGORY_FID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SHP_CATEGORY_FID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SHP_CATEGORY_FID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SHOP_RENT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SHOP_RENT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SHOP_RENT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SHOPKEEPER_FID, "SHOPKEEPER_FID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SHOPKEEPER_FID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SHOPKEEPER_FID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CITY_FID, "CITY_FID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CITY_FID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CITY_FID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

myProject/Views/SHOP_tbl/Delete.cshtml
@model myProject.Models.SHOP_tbl

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SHOP_tbl</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CITY_tbl.CITY_NAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CITY_tbl.CITY_NAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SHP_CATEGORY_tbl.SHP_CATEGORY_NAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SHP_CATEGORY_tbl.SHP_CATEGORY_NAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SHOPKEEPER_tbl.SHOPKEEPER_NAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SHOPKEEPER_tbl.SHOPKEEPER_NAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SHOP_NAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SHOP_NAME)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SHOP_IMAGE)
            <img src="@Url.Content(Model.SHOP_IMAGE)" width="100" height="100" />
        </dt>

       

        <dt>
            @Html.DisplayNameFor(model => model.SHOP_ADDRESS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SHOP_ADDRESS)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SHOP_RENT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SHOP_RENT)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

myProject/Views/SHOP_tbl/Details.cshtml
@model myProject.Models.SHOP_tbl

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>SHOP_tbl</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CITY_tbl.CITY_NAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CITY_tbl.CITY_NAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SHP_CATEGORY_tbl.SHP_CATEGORY_NAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SHP_CATEGORY_tbl.SHP_CATEGORY_NAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SHOPKEEPER_tbl.SHOPKEEPER_NAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SHOPKEEPER_tbl.SHOPKEEPER_NAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SHOP_NAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SHOP_NAME)
        </dd> 
        
        <dt>
            @Html.DisplayNameFor(model => model.SHOP_IMAGE)
        </dt>

        <dd>
            <img src="@Url.Content(Model.SHOP_IMAGE)" width="100" height="100" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SHOP_ADDRESS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SHOP_ADDRESS)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SHOP_RENT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SHOP_RENT)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.SHOP_ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

myProject/Views/SHOP_tbl/Edit.cshtml
@model myProject.Models.SHOP_tbl

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "SHOP_tbl", FormMethod.Post, new {enctype="multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SHOP_tbl</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SHOP_ID)

        <div class="form-group">
            @Html.LabelFor(model => model.SHOP_NAME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SHOP_NAME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SHOP_NAME, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.SHOP_IMAGE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="pic"/>
                <img src="@Url.Content(Model.SHOP_IMAGE) "width="100" height="100"/>

                @Html.HiddenFor(model => model.SHOP_IMAGE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SHOP_IMAGE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SHOP_ADDRESS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SHOP_ADDRESS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SHOP_ADDRESS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SHP_CATEGORY_FID, "SHP_CATEGORY_FID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SHP_CATEGORY_FID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SHP_CATEGORY_FID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SHOP_RENT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SHOP_RENT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SHOP_RENT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SHOPKEEPER_FID, "SHOPKEEPER_FID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SHOPKEEPER_FID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SHOPKEEPER_FID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CITY_FID, "CITY_FID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CITY_FID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CITY_FID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

myProject/Views/SHOP_tbl/Index.cshtml
@model IEnumerable<myProject.Models.SHOP_tbl>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    <a href="@Url.Action("Create","SHOP_tbl")" class="btn btn-danger">Create New</a>
</p>
<table class="table">
    <tr>
        <th>
            City Name
        </th>
        <th>
            Floor Name
        </th>
        <th>
           Shopkeeper Name
        </th>
        <th>
           Shop Name
        </th>
        <th>
           Shop Image
        </th>
        
        <th>
            Shop Address
        </th>
        <th>
            Shop Rent
        </th>
        <th></th>
    </tr>

@foreach (var shop in Model) { 
    <tr>
        <td>
            @shop.CITY_tbl.CITY_NAME
        </td>
        
        <td>
            @shop.SHP_CATEGORY_tbl.SHP_CATEGORY_NAME
        </td>
        <td>
            @shop.SHOPKEEPER_tbl.SHOPKEEPER_NAME
        </td>
        <td>
            @shop.SHOP_NAME
        </td>
        <td>
            <img src="@Url.Content(shop.SHOP_IMAGE)" width="100" height="100"/>
        </td>
        <td>
            @shop.SHOP_ADDRESS
        </td>
        <td>
            @shop.SHOP_RENT
        </td>
        <td>
            <a class="glyphicon glyphicon-pencil btn btn-danger square-btn-adjust" href="@Url.Action("Edit", "SHOP_tbl", new { id = shop.SHOP_ID })"></a>
            <a class="glyphicon glyphicon-book btn btn-danger square-btn-adjust"   href="@Url.Action("Details", "SHOP_tbl", new { id = shop.SHOP_ID })"></a>
            <a class="glyphicon glyphicon-trash btn btn-danger square-btn-adjust" href="@Url.Action("Delete", "SHOP_tbl", new { id = shop.SHOP_ID })"></a>

            
        </td>
   
    </tr>
}

</table>